export const ADD_TO_WISHLIST = "ADD_TO_WISHLIST"
export const REMOVE_FROM_WISHLIST = "REMOVE_FROM_WISHLIST"
export const SET_WISHLIST = "SET_WISHLIST"

export const SET_RECORDS = "SET_RECORDS"
export const ADD_TO_RECORDS = "ADD_TO_RECORDS"
export const UPDATE_RECORD_DETAILS = "UPDATE_RECORD_DETAILS"

export const SET_RECORDSHOP = "SET_RECORDSHOP"

export const ADD_TO_RECORDSHOP = "ADD_TO_RECORDSHOP_RECORDS"
export const UPDATE_RECORDSHOP = "UPDATE_RECORDSHOP_RECORDS"

export const SIGN_UP = "SIGN_UP"
export const LOG_IN =  "LOG_IN"
export const RETURNING = "RETURNING"
export const DELETE_USER = "DELETE_USER"
export const EDIT_USER = "EDIT_USER"
export const LOG_OUT = "LOG_OUT"

export const OWNER_LOG_IN =  "OWNER_LOG_IN"
export const OWNER_RETURNING = "OWNER_RETURNING"
export const OWNER_LOG_OUT = "OWNER_LOG_OUT"